#!/bin/sh
set -e

: ${RUNASME_WORKDIR:=/workdir}
user=${USER:-user}
group=$GROUP

while getopts ":u:g:h" opt; do
  case $opt in
    h)
      echo "By default runs with the ownership (uid:gid) detected from the mounted /workdir folder"
      echo
      echo "If necessary, the name of the user and/or group can be detected from a mount of /etc/passwd"
      echo "and/or /etc/group or specified using environment variables"
      echo
      echo "Environment variables:"
      echo "  RUNASME_WORKDIR  the working directory inside the container, default is /workdir"
      echo "  UID              the user id, if set this will be used instead of the owner of the workdir"
      echo "  GID              the group id, if set this will be used instead of the group of the workdir"
      echo "  USER             the name of the user, will override user name found in /etc/passwd"
      echo "  GROUP            the name of the group, will override group name found in /etc/group"
      exit 0
      ;;
    u)
      user="$OPTARG"
      ;;
    g)
      group="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
shift $(expr $OPTIND - 1 )

uid=${UID:-$(stat -c "%u" "$RUNASME_WORKDIR")}
gid=${GID:-$(stat -c "%g" "$RUNASME_WORKDIR")}

if [ -z $group ]; then
  if [ $uid -eq $gid ]; then group=$user
  else group=group
  fi
fi

# TODO Find out if uid is already in /etc/passwd (and then better use that username unless explicitly configured)
echo "$user:x:$uid:$gid:$user,,,:/home/user:/bin/sh" >> /etc/passwd

# TODO Find out if gid is already in /etc/group (and then better use that group name unles explicityly configured)
echo "$group:x:$gid:" >> /etc/group

[ ! -d /home/user ] && mkdir /home/user
chown $uid:$gid /home/user
chmod 755 /home/user

(cd "$RUNASME_WORKDIR" && sudo HOME=/home/user -E -u $user "$@")
